export const config = {
  site: {
    name: "JfrAziz",
    description: "",
    githubLink: "https://github.com/jfraziz",
    twitterLink: "https://twitter.com/jfraziz"
  },
  wordClouds: {
    words: [
      "Javascript",
      "Typescript",
      "Node.js",
      "Alpine.js",
      "React",
      "Next.js",
      "Express.js",
      "Prisma.js",
      "Data Science",
      "Python",
      "R Studio",
      "Linux",
      "Arch",
      "Bash",
      "PHP",
      "Laravel",
      "Tailwindcss",
      "Docker",
      "Git",
      "GitHub",
      "Automation",
      "Cloudflare",
      "Javascript",
      "Typescript",
      "Node.js",
      "Alpine.js",
      "React",
      "Next.js",
      "Express.js",
      "Prisma.js",
      "Data Science",
      "Python",
      "R Studio",
      "Linux",
      "Arch",
      "Bash",
      "PHP",
      "Laravel",
      "Tailwindcss",
      "Docker",
      "Git",
      "GitHub",
      "Automation",
      "Cloudflare",
    ],
    radius: 28
  },
}