export const config = {
  words: [
    "React",
    "Javascript",
    "Laravel",
    "Typescript",
    "Tailwindcss",
    "Java",
    "Spring",
    "Data Science",
    "Python",
    "R Studio",
    "Next.js",
    "Bash",
    "Linux",
    "PHP",
    "Docker",
    "GIT",
    "Backend",
    "Typescript",
    "Tailwindcss",
    "Java",
    "Spring",
    "R Studio",
    "Next.js",
    "Bash",
    "Linux",
  ],
  radius: 25
}